### ISSUE TITLE
Plugin not working 

### ISSUE THREAD

**Issue by burdoto** [BaliBalo/ScoreSaber#15]
Hi there, the plugin is not working after a reinstall.
Instead of displaying or uploading any statistics, nothing happens, the game still displays the usual 'scoreboards for custom levels are not supported' banner, and no scores are uploaded

**Comment by burdoto** [comment]
After playing a little more, I'm starting to think that mods In general are not working, since some maps load infinitely, which is behavior I know from maps that require mapping extensions while mapping extensions is not installed.

Now I'm a little lost though, since this was tested on a clean beat saber installation and a clean mods installation. I'm kind of lost for ideas what could help

**Comment by burdoto** [comment]
I have investigated further and it appears to be an issue caused by my possibly outdated version of modassistant; either BSIPA was never properly executed or mods were not downloaded into the plugins directory.
Fixing this manually solved the issue.

**Comment by BaliBalo** [comment]
Hey @burdoto, glad you resolved your issue ! As a note if you encounter some new issues in the future, this repo is not for the actual ScoreSaber mod and site, only for the related tools available online at https://scoresaber.balibalo.xyz/

If you have an issue with the actual ScoreSaber mod, I do not think there is an official GitHub repository to report it - you would have to ask about it in [the discord server](https://discord.gg/WpuDMwU)

(sorry about the confusing repo name, it was only private at first but I then got some requests to make it public)
