### ISSUE TITLE
[FR] PlaylistManager features support (Difficulty Highlighting)

### ISSUE THREAD

**Issue by rithik-b** [BaliBalo/ScoreSaber#3]
Heya! I have a couple of requests for the playlist generation in your website for the pp farm tool (one easy to implement and the other may not be possible, if not that is fine)
## Difficulty Highlighting
Starting with the easy bit, there is difficulty highlighting. If you look at the wiki entry [here](https://github.com/rithik-b/PlaylistManager/wiki/Difficulties) you will find the schema for difficulty highlighting used by PlaylistManager. Basically for each song you can highlight one (or multiple) difficulties and they will be visible to the players in the game like this. ![Highlighted Difficulties. The difficulties are shown with yellow text and they turn green when the player selects it.](https://github.com/rithik-b/PlaylistManager/blob/master/img/difficulty.png?raw=true)
However for your website specifically I would suggest instead of using one song with multiple diffs highlighted we could use multiple copies of a song with just a single diff highlighted so it is sorted in the exact same way as the website itself (if the playlist contains the same song with multiple diffs).
## ~~Syncing~~ (no need for this anymore)
This may be a bit tricky as mentioned and the wiki link about this key is [here](https://github.com/rithik-b/PlaylistManager/wiki/SyncURL). Essentially you would need to make a **static** URL that always returns the most up to date version of the playlist for the user and store it in that key. Given that the website generates the playlist on request time I am not entirely sure if it is possible, but if it is possible then it would be an amazing feature to have as players can get the most up to date ranked playlist ingame.
![Playlist Sync](https://github.com/rithik-b/PlaylistManager/blob/master/img/sync.gif?raw=true)

**Comment by BaliBalo** [comment]
Sorry for the delay ! Great ideas. The difficulty stuff seems cool, I will look into adding it soon when I have time, and I will keep you updated.

For the sync, someone already added it to the top200 playlist through https://github.com/BaliBalo/ScoreSaber/pull/2 but adding it to custom playlists generated on peepee (based on scoresaber profiles) is not really easily doable indeed. I would need to keep a cached version of the players completions and update that list with some scoresaber requests for each sync request, which is a lot of work and a lot of requests/data transfer for my small server.  
I could potentially do it a bit more easily for [/playlist-maker](https://scoresaber.balibalo.xyz/playlist-maker) but not sure this one matters too much for most people.

**Comment by rithik-b** [comment]
It's alright, difficulty highlighting should be enough!

**Comment by BaliBalo** [comment]
Hey, sorry for the very long wait on this one, things got a bit busy on my side but I finally got to it ! All playlists generated through the site should now have the difficulty indicator set
